### ISSUE TITLE
[L] Warn A&R user of a variance upon filling out form

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-admin#255]
As a park operator, I want to know when a value I enter into A&R may trigger a variance so that I am aware and can address it accordingly. 

As a BC Parks staff, I want park operators and RSO’s to be aware that the value they are entering is within an expected range so that we get more accurate data and/or are alerted via variance note as to why the value is different or missing.

This ticket is to implement the user facing warning of a variance so that the user can fix it or apply variance right away, and will provide better reporting overall.

**Acceptance Criteria:**

- matches designs (linked below)
- data entry forms within A&R have a variance warning applied
- If a field has a variance outside of +/- 20% range after saving, tooltip shows variance on mouse over
- Tooltip shows average value for that field
- existing the field with the mouse hides the tooltip but keeps the red outline of the field to signal variance
- user is “warned” about variances via trigger pop-up within form upon save action and has the option to continue editing or save and proceed
- adding a variance note will remove the trigger pop-up

**Notes**

- [figma designs](https://www.figma.com/file/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?type=design&node-id=5173%3A15607&mode=design&t=WEfzGhEkkf1trKyc-1)

- can we use form engine invalid field style?
   - https://digitalspace.github.io/ngds-toolkit/forms

**Variance calculation:**
If A is your average or comparison #, and B is your current year's number, the formula is (B-A)/B x 100, answer is a %

Example: 2017-2019 average for frontcountry camping at Bull Canyon Park was 779 people. 2022 attendance was 1,101 people.

(1,101-779)/779 = 0.29 0.29 x 100 = 29%

The 2022 attendance increase by 29% (or has a variance of 29%)

Variance is triggered @ 20% and for anything at or outside that range.

**Comment by JLWade** [comment]
blocked by #291

**Comment by ashley-dhillon** [comment]
Estimate to be provided once the refinement ticket is complete.

**Comment by cameronpettit** [comment]
@manuji @JLWade This is quite a substantial change so I will list what has been done to make things a little easier.

1. On the enter data page, the date, park and subarea forms have all been replaced by the new form engine. Parts of the old engine were too intertwined with this page to leave without updating it.

Aside from the appearance, there should be no major change in the way the fields function except for a few key things:

- The url now updates every time the form changes
- The displayed list of accordions is now wiped when the form changes, to prevent confusion where the shown list of accordions does not correlate to the current field settings. Bring up the new list of accordions by clicking 'Go' again.
- Fixed several console errors that were present in the previous version

2. Every activity form has been recreated from scratch and will need a thorough smoke test to ensure they still function as intended and are hooked up to the correct fields in the API. The appearance and function of the forms should have no major changes except for a few key things:

- The number fields no longer have increment/decrement arrows. They are not present in the original designs. The form engine can bring them back if necessary.
- Money fields automatically format your input to 2 decimal places.
- You should not be able to enter a negative value in any of the fields.

3. If a variance is triggered and you do not provide a note, you will be notified after clicking 'Save'. If you add a note after variances are triggered, the warning tooltips will not disappear until you click 'Save' again. If you provide a note in the first place then no variance will be triggered. 

4. https://github.com/bcgov/bcparks-ar-api/issues/303 is included as part of this ticket.

5. Something interesting I noticed with variance recording (API related and has been present in our code a long time): We round our variance to 2 decimal places, so sometimes a variance is triggered prematurely: if one year is 1000 and the next year is 1195, the variance is 0.195 => 0.20 which triggers even though the new value is less than the threshold. Might want to investigate chopping instead of rounding if this is going to be an issue.

6. I am going to go back and rip out the other forms in A&R and replace them with the form engine, but that task does not block the completion of this ticket.

@manuji If there are QA items that come out of your review, please just list them here instead of making new bug tickets, it will be easier for me to review and implement them that way. Also, please bump the minor version of `bcparks-ar-admin` when you deploy as this change is quite large.

**Comment by cameronpettit** [comment]
Adding https://github.com/bcgov/bcparks-ar-admin/pull/310 to this ticket - replaced the form elements on the following pages:

- Review Data
- Lock Records
- Export Reports

**Comment by manuji** [comment]
Tested on TEST: Pending
Given below are the issues I noticed. 
1. Missing the tooltip when the input field is in "Active" state unless you have the mouse hover over the field. 
2. The Form is missing the facility name on the form heading. 
3. Information displayed on the tooltip for individual fields are incorrect when the form hasn't fully filled in.

**Comment by cameronpettit** [comment]
@manuji @JLWade reviewing the points above:

> 1. Missing the tooltip when the input field is in "Active" state unless you have the mouse hover over the field.

As per the [designs](https://www.figma.com/file/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?type=design&node-id=671-2251&mode=design&t=GZpXVbEXtfk2X7cp-0):
![image](https://github.com/bcgov/bcparks-ar-admin/assets/71421099/e0973b60-b2ca-4512-8e93-a05d0197e184)
Perhaps not explicitly clear in the designs but a tooltip by definition only appears on mouse hover.

> 2. The Form is missing the facility name on the form heading.

I noticed this happening in the video you posted in https://github.com/bcgov/bcparks-ar-api/issues/303#issuecomment-1973887397 but I cannot replicate in TEST. Please provide explicit steps to replicate.

> 3. Information displayed on the tooltip for individual fields are incorrect when the form hasn't fully filled in.

Please provide steps to replicate and what is explicitly expected to be correct.

**Comment by JLWade** [comment]
Just ran through it in TEST and am also unable to replicate 2 and 3. 1 seems to be as expected.

**Comment by cameronpettit** [comment]
@manuji I think I was able to reproduce what you are reporting for number 3 by doing the following:

1. trigger a variance in any field for any activity: when you click submit, wait for the modal to appear.
2. In the modal, click 'continue editing' to review the variances. Take note of the fields that triggered a variance.
3. click 'cancel' in the bottom left corner to give up editing the record. Click 'Discard changes' when the modal appears.
4. You will be navigated back to the accordion list for that subarea. Go back and click 'Edit' on the same activity you just navigated away from.
5. Hover over any fields that had triggered a variance previously. A tooltip will appear even though the `invalid` styling is not applied and the current value of the field may not actually trigger a variance.

I predict this is because the variance settings from the previous screen are not being cleared when navigating away from a record if that record is never saved. I will look into creating a patch for that.

**Comment by cameronpettit** [comment]
Edit: patched this in #317

**Comment by manuji** [comment]
Thank you @cameronpettit

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has been implemented and working as expected. 
* Passing to PO review.

**Comment by JLWade** [comment]
workin as expected moving to done
