### ISSUE TITLE
Backcountry Cabin Form needs updated title

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-admin#286]
Backcountry Cabins form in A&R has the wrong title shown. 
Currently reads Family but should say Gross Backcountry Cabin Revenue.

![Image](https://github.com/bcgov/bcparks-ar-admin/assets/38668130/b5cc37ed-8329-4da6-9f4d-7cd27defca0f)

Acceptance Criteria:
- in backcountry cabin form the title Family reads Gross Backcountry Cabin Revenue

**Comment by manuji** [comment]
Tested on TEST: **Failed**
* The title should read "Gross Backcountry Cabin Revenue" instead of "Gross". 
* Also @JLWade  or @ashley-dhillon , not sure if it was intentionally written in title case in the AC, but to be consistent with the rest of the titles in other facilities I would recommend it to be in sentence case. 


![Image](https://github.com/bcgov/bcparks-ar-admin/assets/65190263/c864a1a2-34ab-4803-b3a1-7b8159b7d042)

**Comment by manuji** [comment]
@JLWade could you please check my previous comment and confirm the correct label to show? Looks like this ticket has been moved back to QA without addressing the issue I have mentioned above. 

fyi @marklise

**Comment by manuji** [comment]
Tested on TEST: **passed**
* Verified that this issue has been fixed. 
* Passed to PO review.

**Comment by JLWade** [comment]
Done - moving to done
