### ISSUE TITLE
Export report shows the status as 100% complete right after it actually starts to export

### ISSUE THREAD

**Issue by manuji** [bcgov/bcparks-ar-admin#364]
Scenario:
* Navigate to the A&R Admin TEST environment. https://d3ahrzu0mpndj3.cloudfront.net/export-reports
* Then navigate to the Export Reports page. 
* Choose one of the report types and select the option to export the report. 
* Check the progress bar and notice what it shows at each point while the export is in progress. 

Expected:
* The export report progress should display accurate statuses to the user. 

Issue:
* Just after the export has started the progress bar shows 100% green line and then starts the actual export. 

https://github.com/user-attachments/assets/f9e227d7-2c01-4ff8-b861-763b339b9b5e

**Comment by meredithom** [comment]
I'm unable to get the video to play, and downloading it displays an error. I am also unable to reproduce the issue:


https://github.com/user-attachments/assets/f1e78809-93e6-45c1-b7bb-b7748cc5b1b8

**Comment by marklise** [comment]
This is not reproducible when using the web application under normal circumstances.  It is however reproducible if you go to multiple tabs and start jobs such as variance and before that job finishes go to another tab and generate a new report for all data. The progress bar percentage is going to report both jobs simultaneously because they are in the background.  To fix this would require a bit of a refactor to the entire page and tab implementation. Not sure this is worth the effort at this time.

@meyerdarcie @meredithom @manuji

**Comment by manuji** [comment]
Thank you @marklise , I confirmed if I am diligent with the export feature then I don't see this bug. I will close this bug.
