### ISSUE TITLE
Explore pulling traffic and counter data through Trafx

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/bcparks-ar-admin#392]
#### Description:

Determine if there is an API or other mechanism to pull traffic and counter data from Trafx into A&R to help automate data entry process for staff. 

#### Acceptance Criteria:
- [x] Determine if there is an API available
- [x] Explore what is needed to pull/ingest data into our system
- [x] Get a walk through of Trafx from A&R team
- [x] Determine if any data manipulation may be required
- [ ] Create future tickets as needed (e.g., ability to correct data once in system)

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
This was discussed at the October 11 prioritization session. Additional notes from the conversation:

- Explore what is possible
- What does it look like to get the API
- Determine if any data manipulation is required
- Get a walk through of Trafx
- Would need a way to correct the data (traffic counters are error prone)

**Comment by LindsayMacfarlane** [comment]
Previous documentation done by RST to link to Trafx api:

[p_&_r_visitor_statistics_report_and_dashboard_prototype_technical_document_v2.docx](https://bcgov.sharepoint.com/:w:/r/teams/00739/Shared%20Documents/Project%20-%20Rec%20Visitor%20Statistics%20Modernization/4%20-%20Data/CWU%20-%20Okanagan%20Area%20Prototype/Documentation/p_%26_r_visitor_statistics_report_and_dashboard_prototype_technical_document_v2.docx?d=w75d3254459f24d7d91f6a7ac2a425f46&csf=1&web=1&e=RUkcgO&xsdata=MDV8MDJ8fDYyNDBlMzIwZGQxYjRkM2FhODI2MDhkY2VhNDVmYzkyfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2Mzg2NDI4MzM0OTA4ODA1NTB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMM1JsWVcxekx6RTVPamRuWnpOd2VIcHZUQzFvYWxwU1NIWnlOV2RuYTJwNFVEbFBPR05oYURaVFYzRnBXV2w2TWtORVgwMHhRSFJvY21WaFpDNTBZV04yTWk5amFHRnVibVZzY3k4eE9UbzNaMmN6Y0hoNmIwd3RhR3BhVWtoMmNqVm5aMnRxZUZBNVR6aGpZV2cyVTFkeGFWbHBlakpEUkY5Tk1VQjBhSEpsWVdRdWRHRmpkakl2YldWemMyRm5aWE12TVRjeU9EWTROalE1TmpBNU5BPT18ZWIwN2NiODk2MzdhNDA1YWE4MjYwOGRjZWE0NWZjOTJ8Y2ViOWM2NzRiZTFmNGMxY2IzNWI3ZDk5N2EzY2NkNGU%3D&sdata=UVpxY2hYaVJ6QlgzcWk2TVI3VXZ0UWlIRk5ncXZDREhBeE53dnRCYm9vST0%3D&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CLindsay.Macfarlane%40gov.bc.ca)
code is in bcgov-c for now but some of you may have access and uses OpenSearch!
https://github.com/bcgov-c/rvs-card/blob/main/README.md

**Comment by davidclaveau** [comment]
> Previous documentation done by RST to link to Trafx api:
> 
> [p_&_r_visitor_statistics_report_and_dashboard_prototype_technical_document_v2.docx](https://bcgov.sharepoint.com/:w:/r/teams/00739/Shared%20Documents/Project%20-%20Rec%20Visitor%20Statistics%20Modernization/4%20-%20Data/CWU%20-%20Okanagan%20Area%20Prototype/Documentation/p_%26_r_visitor_statistics_report_and_dashboard_prototype_technical_document_v2.docx?d=w75d3254459f24d7d91f6a7ac2a425f46&csf=1&web=1&e=RUkcgO&xsdata=MDV8MDJ8fDYyNDBlMzIwZGQxYjRkM2FhODI2MDhkY2VhNDVmYzkyfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2Mzg2NDI4MzM0OTA4ODA1NTB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMM1JsWVcxekx6RTVPamRuWnpOd2VIcHZUQzFvYWxwU1NIWnlOV2RuYTJwNFVEbFBPR05oYURaVFYzRnBXV2w2TWtORVgwMHhRSFJvY21WaFpDNTBZV04yTWk5amFHRnVibVZzY3k4eE9UbzNaMmN6Y0hoNmIwd3RhR3BhVWtoMmNqVm5aMnRxZUZBNVR6aGpZV2cyVTFkeGFWbHBlakpEUkY5Tk1VQjBhSEpsWVdRdWRHRmpkakl2YldWemMyRm5aWE12TVRjeU9EWTROalE1TmpBNU5BPT18ZWIwN2NiODk2MzdhNDA1YWE4MjYwOGRjZWE0NWZjOTJ8Y2ViOWM2NzRiZTFmNGMxY2IzNWI3ZDk5N2EzY2NkNGU%3D&sdata=UVpxY2hYaVJ6QlgzcWk2TVI3VXZ0UWlIRk5ncXZDREhBeE53dnRCYm9vST0%3D&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CLindsay.Macfarlane%40gov.bc.ca) code is in bcgov-c for now but some of you may have access and uses OpenSearch! https://github.com/bcgov-c/rvs-card/blob/main/README.md

Hey @LindsayMacfarlane!

I don't seem to have access to that first `docx` document (I made a request on Friday through that SharePoint Access Request screen it sends me to, but no change yet), and I get a 404 for the second link to the repo, so it must be hidden for me 😅

Just wondering if there's another way to access these or if you have the power to share them with me?

**Comment by LindsayMacfarlane** [comment]
@davidclaveau - I've given you access to the word doc - let me know if that didn't work. 

@JLWade - are you able to grant us access to this gitHub re. Trafx and RST? It comes up as a 404

- https://github.com/bcgov-c/rvs-card/blob/main/README.md

**Comment by JLWade** [comment]
the word docs might be the most useful - I dont think they were able to connect to TrafX in the end but did do some initial research on it

**Comment by davidclaveau** [comment]
Thanks @LindsayMacfarlane  and @JLWade! I'll look through the doc and report my findings!

**Comment by davidclaveau** [comment]
Findings:

- Trafx does not have an API that we can use for integrating with A&R.
- RST team was speculating a setup to import data from Trafx (and other data sources) into AWS OpenSearch to index and report visitor statistics.
  - This is probably overkill for data from Trafx alone, but could be considered if these other data sources are used for cross-referencing in A&R reporting
- I will be speaking with the A&R team later this week about Trafx and how the data is exported/used by POs and entered into A&R.
  - One possible solution (so far) is a simple import system for `.xlsx` or `.csv` files, which would upload and allocate the data from a Trafx export into A&R.

**Comment by davidclaveau** [comment]
Had a great walkthrough with Nicole, discussed TRAFx and the setup of the system:

### TRAFx rundown:
- There are several accounts that cover several different regions for BC Parks
- Park Operators upload trail data from the TRAFx devices into TRAFx
- TRAFx consolidates the data and allows for easy visualization of the data in their dashboard
- This data can also be downloaded as an Excel spreadsheet and provides trail information by month and year
 - If there are several subareas and several trails on top of that, it can be available in a single export

### _Rough_ thoughts for implementation with A&R
- TRAFx users take a bulk export of trail data and upload the spreadsheet to a designated page on A&R
- This designated page sorts the trail data based on the user's access to parks (i.e. can only upload trail data for a park/subarea they have access to)
- After uploading this data, A&R standardizes the report and distributes the trail data to their respective subareas
- It would be preferred that, before saving this data, the user was asked to confirm the data once more before it's saved to a subarea, i.e. "you are adding X number of attendees to this subarea for Y month" and/or "you are overwriting data here: ________"
- We would allows users to manually change these data points before/after it's uploaded, so it would be preferred to flag if the data was uploaded manually or by bulk import (`bulkImport == true`)

### Some underlying issues:
- We would most likely encounter issues with importing this information in bulk because there isn't a _great way_ to connect trails with their subareas, outside of doing a string comparison
  - We _could_ hard-code a data register in A&R to sort trails to their respective subareas, e.g. Buttle Lake trail always goes to Buttle Lake in A&R, but then we're responsible for maintaining that register manually with any changes.
  - We could also encounter issues with typos/user-input error
  - Also also, if there was a name change to a trail, we would need to update the trail data register on our end.
  - **If every trail in TRAFx tracked what its subarea ID was in A&R, then a name change would be inconsequential.**

**Comment by davidclaveau** [comment]
Some thoughts and questions about creating a TRAFx importer in A&R. I'll look to create some tickets in the backlog for the team to discuss further!

![Image](https://github.com/user-attachments/assets/895004f4-0278-4344-8fbd-1f8c6f96d9c7)

**Comment by LindsayMacfarlane** [comment]
@davidclaveau - great research and analysis. I'm curious about estimated effort/cost to implement before we move forward with anything.

**Comment by davidclaveau** [comment]
@LindsayMacfarlane I can't say too much about the cost, but keeping the imported CSVs in an S3 bucket would be a very low cost from what I've been told.

As for the effort, that's probably a bit trickier - I'd be interested in others' input in backlog refinement or wherever we discuss this. To me, it's not a _huge_ feature addition, but it does mean some bigger UI changes on the frontend for the importer landing page and confirmation page, and a fair bit of logic for the importer's data transformation/validation/input and any error handing. Also an update to the UI for showing manual vs. imported data.

**Comment by LindsayMacfarlane** [comment]
Thanks again @davidclaveau for all your research and recommendations. Would love to take this back to Sally, Nicole and team to better understand next steps and how we may want to move this forward.

**Comment by Dianadec** [comment]
Note: would need to address the double-counting that can happen
