### ISSUE TITLE
Design for variance reasons

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/bcparks-ar-admin#396]
#### Description:

Design for how we can implement reasons for variances in A&R. 

A&R will share the list of common variance options. Context: This list will be matched up with list used in staff advisory portal for consistency

Needs:

- pre-determined list of reasons for variances they can select (dev preference: everything they can possibly think of, IN ADDITION to the 10 main things) Sub categories too. SEE HERE FOR LIST: https://github.com/bcgov/bcparks-ar-admin/issues/393#issuecomment-2418083944
- including one where they can write their own
- can select multiple
- good for metrics
- compliance for A&R to have the variance
- trying to reduce friction for them to comply

#### Acceptance Criteria:
- Designs that capture the above needs
- implementation ticket (#393) has been updated with AC according to designs

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking #393 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Standardized variances - working copy - https://bcgov.sharepoint.com/:x:/r/teams/031072/Shared%20Documents/Attendance%20and%20Revenue/Variance/Standardised%20Variances-%20working%20copy.xlsx?d=w6e4eda1261f1465fb8036c7d96ff7fad&csf=1&web=1&e=HMUkq2

**Comment by Dianadec** [comment]
Sprint planning notes:
Rob - doesn't have definitions anywhere documented but can reach out to Rob or Brett for definitions.
Jane - said there were plans to get rid of event types - but Rob said this isn't the case to change them unless adding new ones.

Question: for POs do we need a list of definitions so that they know which one is which?
Sally: we should ideally have definitions somewhere. Data could be done by an admin staff or temp worker.

Not having definitions doesn't block this work.

92 standard event types. Not a lot are relevant to A&R.

Some will not be captured by BC Parks that will be in A&R eg: Counter. If the counter is missing/broken/unavail - it affects the calculation - but bc parks won't have that as an event type.

Best practice - don't link away to definitions.

Pavel - going to meet later to discuss this more.

**Comment by meredithom** [comment]
Moving to blocked until after meeting with A&R and BcParks.ca teams.

**Comment by meredithom** [comment]
Designs updated in [A&R Figma](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=6066-14908&t=OT40O1EteVI8WDu8-1)

Category list:
[Variance Categories.xlsx](https://github.com/user-attachments/files/18190932/Variance.Categories.xlsx) (see first page)

Behaviour:
- Dropdown added for variance reason on form pages
- Certain categories have a subcategory that doesn't need to be visible at all times

Notes:
- Decided to omit required state on variance boxes as there is no current way to save a draft. Open to discussions on this. 
- Decided to keep the list the same for each activity as there's not too many options to scroll through.
- Linking to BCParks.ca for EventTypes isn't possible due to the fact that the events often happen at a park level and sub-areas are not synced between the systems.

**Comment by LindsayMacfarlane** [comment]
Designs look great @meredithom! One quick question I have: One design includes sub-area and one design doesn't. Can you confirm which one we would be implementing? Is it the one with sub-category?

**Comment by meredithom** [comment]
I'm assuming you mean the subcategory, not sub-area? It only needs to be visible **if the main category has a subcategory**. In the excel sheet I attached you can see all the options on the first page and only some have a subcategory. Let me know if you have any more questions!

**Comment by LindsayMacfarlane** [comment]
Thank you @meredithom ! That is the clarification I needed :)
